nav:

    - Home: index.md
    - Platforms: 
      - platforms/index.md
    - Data & Analysis Platform: 
        - data/index.md
    - Development Platform: 
        - developer/index.md
    - Integration Platform: 
        - integration/index.md
    - Publications: 
      - publications/index.md
      - Reports: reports
    - FAQ: faq.md
